/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kPa3GHLjWOc
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from './ui/button'
import { Input } from './ui/input'

export function SearchBar() {
	return (
		<div className="flex w-full max-w-sm items-center space-x-2">
			<Input type="search" placeholder="Search..." />
			<Button type="submit" variant="outline" className="h-9 w-9 flex items-center justify-center rounded-full">
				<span className="sr-only">Search</span>
				<div className="w-4 h-4" />
			</Button>
		</div>
	)
}
